# Generated by Django 3.0.8 on 2020-07-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('precise', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun', models.FloatField()),
                ('moon', models.FloatField()),
                ('mercury', models.FloatField()),
                ('venus', models.FloatField()),
                ('mars', models.FloatField()),
                ('jupiter', models.FloatField()),
                ('saturn', models.FloatField()),
                ('uranus', models.FloatField()),
                ('neptune', models.FloatField()),
                ('pluto', models.FloatField()),
                ('tnode', models.FloatField()),
                ('mnode', models.FloatField()),
                ('lilit', models.FloatField()),
                ('chiron', models.FloatField()),
                ('natus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='astrology.Nata')),
            ],
        ),
        migrations.AddField(
            model_name='nata',
            name='category',
            field=models.ManyToManyField(to='astrology.Tipo'),
        ),
    ]
